
# ▄▀█ █░█ ▀█▀ █▀█ █▀ ▀█▀ ▄▀█ █▀█ ▀█▀
# █▀█ █▄█ ░█░ █▄█ ▄█ ░█░ █▀█ █▀▄ ░█░

# Wallpaper & Colors
exec-once = ~/.config/hypr/scripts/startup.sh

# Daemons
exec-once = waybar
exec-once = systemctl --user start hyprpolkitagent
exec-once = mako

# Dock
exec-once = nwg-dock-hyprland -c "rofi -show drun -replace" -x -i 36 -mb 10

# Numlock
exec-once = numlockx on

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

# Clipboard
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

