
# █▀█ █▀█ █▀█ █▀▀ █▀█ ▄▀█ █▀▄▀█ █▀
# █▀▀ █▀▄ █▄█ █▄█ █▀▄ █▀█ █░▀░█ ▄█


# Applications
$terminal = kitty
$filemanager = thunar
$menu = rofi -show drun
$browser = google-chrome-stable
$lockscreen = hyprlock
$logout = wlogout
$discord = vesktop
$code = code
$spotify = spotify
$screenshot_region = hyprshot -m region -o ~/Pictures/Screenshots -z -s
$screenshot_screen = hyprshot -m output -o ~/Pictures/Screenshots -z -s
$clipboard = bash -c 'cliphist list | rofi -dmenu -i -p Clipboard | cliphist decode | wl-copy'


# Shell Scripts
$reloader = ~/.config/hypr/scripts/reloader.sh
$wallsify = ~/.config/hypr/scripts/wallsify.sh
$hypredit = ~/.config/hypr/scripts/hypredit.sh
$updater = ~/.config/hypr/scripts/updater.sh
$gamemode = ~/.config/hypr/scripts/gamemode.sh
