
# █░█ █▄█ █▀█ █▀█ █░░ ▄▀█ █▄░█ █▀▄   █▀▀ █▀█ █▄░█ █▀▀ █ █▀▀
# █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▀█ █░▀█ █▄▀   █▄▄ █▄█ █░▀█ █▀░ █ █▄█

## Sources ##

# Monitors
source = ~/.config/hypr/settings/monitors.conf

# Programs
source = ~/.config/hypr/settings/programs.conf

# Autostart
source = ~/.config/hypr/settings/autostart.conf

# Environment Variables
source = ~/.config/hypr/settings/variables.conf

# Look and Feel
source = ~/.config/hypr/settings/looks.conf

# Animations
source = ~/.config/hypr/settings/animations.conf

# Input
source = ~/.config/hypr/settings/input.conf

# Keybinds
source = ~/.config/hypr/settings/keybinds.conf

# Windows and Workspaces
source = ~/.config/hypr/settings/windows-workspaces.conf

animation_duration=0.0
