# Hyprlock Config

general {
    grace = 1
    fractional_scaling = 2
    immediate_render = true
}

background {
    monitor =
    path = screenshot
    color = rgba(0, 0, 0, 0.5)
    blur_passes = 2
}

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = rgba(255, 255, 255, 1) 
    font_size = 112
    font_family = JetBrainsMono Nerd Font
    shadow_passes = 0
    shadow_size = 0

    position = 0, 220
    halign = center
    valign = center
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = rgba(255, 255, 255, 1) 
    font_size = 112
    font_family = JetBrainsMono Nerd Font
    shadow_passes = 0
    shadow_size = 0

    position = 0, 80
    halign = center
    valign = center
}

# Today
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    color = rgba(255, 255, 255, 1) 
    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = 0, -15
    halign = center
    valign = center
}

# Week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = rgba(255, 255, 255, 1) 
    font_size = 14
    font_family = JetBrainsMono Nerd Font 10

    position = 0, -40
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0

    dots_size = 0.25 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.5 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rouding = -1

    rounding = 500
    inner_color = rgba(255, 255, 255, 0.1) 
    font_color = rgba(255, 255, 255, 1) 
    fade_on_empty = true

    position = 0, 120
    halign = center
    valign = bottom
}
