# Kitty Config

# Pywal colors
include ~/.cache/wal/colors-kitty.conf

# Terminal window
window_padding_width       20
confirm_os_window_close    0
background_opacity         0.8
dynamic_background_opacity 1

# Fonts
font_family      family="JetBrains Mono"
font_size          14
bold_font          auto
italic_font        auto
bold_italic_font   auto

# Cursor
shell_integration  no-cursor
cursor_shape       beam

# Scrolling
scrollback_lines        2000
wheel_scroll_min_lines  1

# Scrollbar
scrollbar_handle_opacity       0
scrollbar_track_opactiy        0
scrollbar_track_hover_opacity  0

# Experimental configurations
cursor_trail 1




# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
